# Generated by Django 3.0 on 2020-10-27 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20201026_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tickets.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_url', models.URLField(null=True)),
                ('subject', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('High - Production System Down', 'HIGH'), ('Med', 'MED - System Impaired'), ('Low', 'LOW - General Guidence')], max_length=30, null=True)),
                ('created_on', models.DateField()),
                ('attach_file', models.FileField(upload_to='media/attachment_records/', verbose_name='Data File')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_categ', to='tickets.Category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_dept', to='tickets.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticekt_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categ_dept', to='tickets.Department'),
        ),
    ]
